services:
  app:
    container_name: challenge_app
    build:
      context: ../LuisaChallenge 
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./src/main:/app/src/main
    restart: always
    networks:
      - challenge_network
    platform: linux/arm64
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    container_name: challenge_mariadb
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=mydatabase'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=verysecret'
      - 'MARIADB_USER=myuser'
    ports:
      - '3306:3306'
    networks:
        - challenge_network
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    platform: linux/arm64
  front:
      image: node:20.17-alpine
      container_name: front
      working_dir: /app
      ports:
        - 3000:3000
      volumes:
        - .:/app
      command: sh -c "npm install && npm run dev"
      environment:
        - NODE_ENV=development
      networks:
        - challenge_network
      platform: linux/arm64
networks:
  challenge_network:
    driver: bridge